# Site settings
title: Rex's Blog
email: rexpie@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Soft sides and blind spots of IOT, hardware, Arduino.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rexpie.github.io" # the base hostname & protocol for your site

github_username:  rexpie

# Build settings
